dockerauth:
  image: cesanta/docker_auth
  ports:
    - "5001:5001"
  volumes:
    - ./config:/config:ro
    - ./logs:/logs
    - ./ssl:/ssl
  command: /config/auth_config.yml
  restart: always

registry:
  image: registry:latest
  ports:
    - "5000:5000"
  volumes:
    - ./ssl:/ssl
    - ./registry:/var/lib/registry
  restart: always
  environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    - REGISTRY_AUTH=token
    - REGISTRY_AUTH_TOKEN_REALM=https://localhost:5001/auth
    - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
    - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem
